[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[dev]
  command = "hugo server"
  publish = "public"
  targetPort = 1313
  port = 8888

[build.environment]
  HUGO_VERSION = "0.122.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

# Rewrite a path
[[redirects]]
from = "/test/0.1.0/*"
to = "https://release-0-1-0--ianmadd-docs-test.netlify.app/test/0.1.0/:splat"
status = 200

[[redirects]]
from = "/test/0.2.0/*"
to = "https://release-0-2-0--ianmadd-docs-test.netlify.app/test/0.2.0/:splat"
status = 200

[[redirects]]
from = "/images/test/0.2.0/*"
to = "https://release-0-2-0--ianmadd-docs-test.netlify.app/images/test/0.2.0/:splat"
status = 200

[[redirects]]
from = "test/0.3.0/*"
to = "https://release-0-3-0--ianmadd-docs-test.netlify.app/:splat"
status = 200